Fix swapped assertion arguments in FirmwareDtboVerification
JUnit assertEquals expects (message, expected, actual). Swapping these
leads to highly confusing error messages like "expected: <FAILED> but was: <SUCCESS>".
Correct the order to restore logical error reporting.

Bug: 499193592
Bug: 493533717
Test: Manual review of diff
(cherry-picked from commit 2a74ec30539736983163971e0dfaad9743f52e2c)

Change-Id: I81836b1ae3e7befa0cabddb7f4a8f82e86c8b1ef